[webservers]
web-1 ansible_host=111.88.255.130 fqdn=fhmer3sivtnmgtsebc78.auto.internal
web-2 ansible_host=111.88.253.14 fqdn=fhmcfo2s74mmnob64kmf.auto.internal

[databases]
main ansible_host=111.88.242.139 fqdn=fhmgtmp04f870kml6873.auto.internal
replica ansible_host=51.250.8.88 fqdn=fhmog2pmupjr2c7krgfa.auto.internal

[storage]
storage ansible_host=93.77.183.103 fqdn=fhmkv1s844ka64e77stt.auto.internal
